include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "lib/app/routes/*.dart"

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_relative_imports: true
    directives_ordering: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_pub_dependencies: true
    avoid_void_async: true
    sort_child_properties_last: true
